Update exampels and docs for resource.name contains
common-fate/terraform-provider-commonfate pull request #146
Opened 2024-11-08 07:04 UTC by JoshuaWilkes

2024-11-10 21:11 UTC, ckluy31 requested changes

2024-11-10 23:46 UTC, JoshuaWilkes commented on examples/resources/commonfate_entra_group_availabilities/commonfate_entra_group_selector/resource.tf
> +  resource.name like "*production*
```suggestion
  resource.name like "*production*"
```

2024-11-10 23:46 UTC, JoshuaWilkes commented on examples/resources/commonfate_entra_group_selector/resource.tf
> +  resource.name like "*production*
```suggestion
  resource.name like "*production*"
```

2024-11-10 23:46 UTC, JoshuaWilkes commented on examples/resources/commonfate_okta_group_selector/resource.tf
> +  resource.name like "*production*
```suggestion
  resource.name like "*production*"
```

2024-11-10 23:46 UTC, JoshuaWilkes commented on internal/auth0/resource_auth0_organization_selector.go
> +				MarkdownDescription: "A Cedar expression with the criteria to match groups on, e.g: ``resource.name like \"*production*\"`",
```suggestion
				MarkdownDescription: "A Cedar expression with the criteria to match groups on, e.g: `resource.name like \"*production*\"`",
```

2024-11-11 00:22 UTC, JoshuaWilkes commented on docs/resources/entra_group_selector.md
> +  resource.name like "*production*"
This one should not have the `

2024-11-11 00:23 UTC, ckluy31 approved these changes

2024-11-11 00:23 UTC, merged